import { Router } from 'express';
import { authRoutes } from '../auth.routes';
import { userRoutes } from '../user.routes';
import { branchRoutes } from '../branch.routes';
import { inventoryRoutes } from '../inventory.routes';
import { masterDataRoutes } from '../masterData.routes';
import { imeiRoutes } from '../imei.routes';
import { supplierRoutes } from '../supplier.routes';
import { purchaseRoutes } from '../purchase.routes';
import { posRoutes } from '../pos.routes';
import { repairRoutes } from '../repair.routes';
import { refurbishRoutes } from '../refurbish.routes';
import { exchangeRateRoutes } from '../exchangeRate.routes';
import { reportRoutes } from '../report.routes';
import { importRoutes } from '../import.routes';
import { auditRoutes } from '../audit.routes';
import { roleRoutes } from '../role.routes';
import { permissionRoutes } from '../permission.routes';
import { transferRoutes } from '../transfer.routes';
import { phoneDatabaseRoutes } from '../phoneDatabase.routes';
import { deviceGradeRoutes } from '../deviceGrade.routes';
import { aiRoutes } from '../ai.routes';
import { deviceSpecsRoutes } from '../deviceSpecs.routes';
import { uploadRoutes } from '../upload.routes';
import { stockMovementRoutes } from '../stockMovement.routes';
import { stockAlertRoutes } from '../stockAlert.routes';
import { logsRoutes } from '../logs.routes';
import { pdfRoutes } from '../pdf.routes';
import { warrantyRoutes } from '../warranty.routes';
import { customerRoutes } from '../customer.routes';
import { activityLogRoutes } from '../activityLog.routes';
import { companyRoutes } from '../company.routes';
import { systemRoutes } from '../system.routes';
import { adminRoutes } from '../admin.routes';
import { setupRoutes } from '../setup.routes';
import { apiKeyRoutes } from '../apiKey.routes';
import { webhookRoutes } from '../webhook.routes';
import { integrationLogRoutes } from '../integrationLog.routes';
import { locationRoutes } from '../location.routes';
import { authMiddleware } from '../../middlewares/auth.middleware';
import { syncRoutes } from '../sync.routes';

const v1Router = Router();

// Public
v1Router.use('/auth', authRoutes);
v1Router.use('/setup', setupRoutes);

// Protected
v1Router.use('/roles', authMiddleware, roleRoutes);
v1Router.use('/permissions', authMiddleware, permissionRoutes);
v1Router.use('/users', authMiddleware, userRoutes);
v1Router.use('/branches', authMiddleware, branchRoutes);
v1Router.use('/inventory', authMiddleware, inventoryRoutes);
v1Router.use('/master-data', authMiddleware, masterDataRoutes);
v1Router.use('/imei', authMiddleware, imeiRoutes);
v1Router.use('/suppliers', authMiddleware, supplierRoutes);
v1Router.use('/purchases', authMiddleware, purchaseRoutes);
v1Router.use('/pos', authMiddleware, posRoutes);
v1Router.use('/repairs', authMiddleware, repairRoutes);
v1Router.use('/refurbish', authMiddleware, refurbishRoutes);
v1Router.use('/transfers', authMiddleware, transferRoutes);
v1Router.use('/phone-database', authMiddleware, phoneDatabaseRoutes);
v1Router.use('/device-grades', authMiddleware, deviceGradeRoutes);
v1Router.use('/ai', authMiddleware, aiRoutes);
v1Router.use('/device-specs', authMiddleware, deviceSpecsRoutes);
v1Router.use('/exchange-rates', authMiddleware, exchangeRateRoutes);
v1Router.use('/reports', authMiddleware, reportRoutes);
v1Router.use('/import', authMiddleware, importRoutes);
v1Router.use('/audit', authMiddleware, auditRoutes);
v1Router.use('/stock-movements', authMiddleware, stockMovementRoutes);
v1Router.use('/stock-alerts', authMiddleware, stockAlertRoutes);
v1Router.use('/logs', authMiddleware, logsRoutes);
v1Router.use('/upload', authMiddleware, uploadRoutes);
v1Router.use('/pdf', authMiddleware, pdfRoutes);
v1Router.use('/warranty', authMiddleware, warrantyRoutes);
v1Router.use('/customers', authMiddleware, customerRoutes);
v1Router.use('/activity', authMiddleware, activityLogRoutes);
v1Router.use('/api-keys', authMiddleware, apiKeyRoutes);
v1Router.use('/webhooks', authMiddleware, webhookRoutes);
v1Router.use('/integration-logs', authMiddleware, integrationLogRoutes);
v1Router.use('/locations', authMiddleware, locationRoutes);
v1Router.use('/sync', authMiddleware, syncRoutes);
v1Router.use('/company', authMiddleware, companyRoutes);
v1Router.use('/system', systemRoutes);
v1Router.use('/admin', adminRoutes);

export { v1Router };
