import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import toast from 'react-hot-toast';

import { PageLayout, PageHeader, TableWrapper } from '../components/design-system';
import { translationsApi } from '../services/api';
import { getErrorMessage } from '../utils/getErrorMessage';

type Lang = 'en' | 'zh' | 'ar' | 'ur';

type Row = {
  id: string;
  key: string;
  languageCode: Lang;
  value: string;
  isAutoGenerated: boolean;
  isVerified: boolean;
  updatedAt?: string;
};

export function TranslationsAdminPage() {
  const { t } = useTranslation();
  const [lang, setLang] = useState<Lang>('ar');
  const [search, setSearch] = useState('');
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<{ key: string; value: string; languageCode: Lang; isVerified: boolean } | null>(null);
  const [missingKeys, setMissingKeys] = useState<string[]>([]);

  const load = async () => {
    setLoading(true);
    try {
      const [{ data: list }, { data: missing }] = await Promise.all([
        translationsApi.list({ languageCode: lang, search: search.trim() || undefined, limit: 500 }),
        translationsApi.missing(lang),
      ]);
      setRows(Array.isArray(list) ? (list as any) : []);
      setMissingKeys(Array.isArray((missing as any)?.missingKeys) ? (missing as any).missingKeys : []);
    } catch (err: any) {
      toast.error(getErrorMessage(err, t('common.failed')));
      setRows([]);
      setMissingKeys([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lang]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return rows;
    return rows.filter((r) => String(r.key).toLowerCase().includes(q) || String(r.value).toLowerCase().includes(q));
  }, [rows, search]);

  const saveEdit = async () => {
    if (!editing) return;
    try {
      await translationsApi.upsert({
        key: editing.key,
        languageCode: editing.languageCode,
        value: editing.value,
        isVerified: editing.isVerified,
      });
      toast.success(t('common.updatedSuccessfully', { defaultValue: 'Updated successfully' }));
      setEditing(null);
      await load();
    } catch (err: any) {
      toast.error(getErrorMessage(err, t('common.failed')));
    }
  };

  const toggleVerify = async (row: Row) => {
    try {
      await translationsApi.verify({ key: row.key, languageCode: row.languageCode, isVerified: !row.isVerified });
      await load();
    } catch (err: any) {
      toast.error(getErrorMessage(err, t('common.failed')));
    }
  };

  const autoFill = async () => {
    try {
      const { data } = await translationsApi.autoFill({ targetLanguageCode: lang, limit: 200 });
      toast.success(
        `${t('common.updatedSuccessfully', { defaultValue: 'Updated successfully' })} (${String((data as any)?.created ?? '')})`
      );
      await load();
    } catch (err: any) {
      toast.error(getErrorMessage(err, t('common.failed')));
    }
  };

  return (
    <PageLayout className="page">
      <PageHeader
        title={t('developer.translations', { defaultValue: 'Translations' })}
        subtitle={t('developer.translationsSubtitle', { defaultValue: 'AI-assisted translation management (verified > auto > English)' })}
      />

      <div className="card" style={{ padding: 16 }}>
        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>
          <label style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <span>{t('languages.chooseLanguage', { defaultValue: 'Choose language' })}</span>
            <select value={lang} onChange={(e) => setLang(e.target.value as Lang)}>
              <option value="en">en</option>
              <option value="zh">zh</option>
              <option value="ar">ar</option>
              <option value="ur">ur</option>
            </select>
          </label>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder={t('common.search', { defaultValue: 'Search' })}
            style={{ minWidth: 220 }}
          />
          <button className="btn btn-secondary" onClick={() => void load()} disabled={loading}>
            {t('common.refresh', { defaultValue: 'Refresh' })}
          </button>
          <button className="btn btn-primary" onClick={() => void autoFill()} disabled={loading || lang === 'en'}>
            {t('developer.autoFillMissing', { defaultValue: 'Auto-fill missing (AI)' })}
          </button>
          <span style={{ color: 'var(--text-secondary)', fontSize: 12 }}>
            {t('developer.missingCount', { defaultValue: 'Missing' })}: {missingKeys.length}
          </span>
        </div>
      </div>

      <TableWrapper>
        <table className="data-table">
          <thead>
            <tr>
              <th style={{ width: 360 }}>{t('developer.key', { defaultValue: 'Key' })}</th>
              <th>{t('developer.value', { defaultValue: 'Value' })}</th>
              <th style={{ width: 140 }}>{t('developer.status', { defaultValue: 'Status' })}</th>
              <th style={{ width: 220 }}>{t('common.actions', { defaultValue: 'Actions' })}</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((r) => (
              <tr key={r.id}>
                <td>
                  <code>{r.key}</code>
                </td>
                <td style={{ whiteSpace: 'pre-wrap' }}>{r.value}</td>
                <td>
                  {r.isVerified ? (
                    <strong>{t('developer.verified', { defaultValue: 'Verified' })}</strong>
                  ) : r.isAutoGenerated ? (
                    <span>{t('developer.auto', { defaultValue: 'Auto' })}</span>
                  ) : (
                    <span>{t('developer.manual', { defaultValue: 'Manual' })}</span>
                  )}
                </td>
                <td>
                  <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                    <button
                      className="btn btn-secondary btn-sm"
                      onClick={() =>
                        setEditing({ key: r.key, languageCode: r.languageCode, value: r.value, isVerified: r.isVerified })
                      }
                    >
                      {t('common.edit', { defaultValue: 'Edit' })}
                    </button>
                    <button className="btn btn-secondary btn-sm" onClick={() => void toggleVerify(r)}>
                      {r.isVerified ? t('developer.unverify', { defaultValue: 'Unverify' }) : t('developer.verify', { defaultValue: 'Verify' })}
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {!loading && filtered.length === 0 ? (
              <tr>
                <td colSpan={4} className="data-table-empty-cell">
                  {t('common.noData', { defaultValue: 'Nothing to show yet.' })}
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </TableWrapper>

      {editing ? (
        <div className="card" style={{ padding: 16, marginTop: 16 }}>
          <h3 style={{ marginTop: 0 }}>
            {t('common.edit', { defaultValue: 'Edit' })} <code>{editing.key}</code> ({editing.languageCode})
          </h3>
          <textarea
            value={editing.value}
            onChange={(e) => setEditing((p) => (p ? { ...p, value: e.target.value } : p))}
            rows={5}
            style={{ width: '100%' }}
          />
          <label style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 10 }}>
            <input
              type="checkbox"
              checked={editing.isVerified}
              onChange={(e) => setEditing((p) => (p ? { ...p, isVerified: e.target.checked } : p))}
            />
            {t('developer.markVerified', { defaultValue: 'Mark as verified' })}
          </label>
          <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
            <button className="btn btn-primary" onClick={() => void saveEdit()}>
              {t('common.save', { defaultValue: 'Save' })}
            </button>
            <button className="btn btn-secondary" onClick={() => setEditing(null)}>
              {t('common.cancel', { defaultValue: 'Cancel' })}
            </button>
          </div>
        </div>
      ) : null}
    </PageLayout>
  );
}

