/**
 * Single source of truth: Prisma models that carry `companyId` and must be tenant-scoped.
 * Models without a direct `companyId` (e.g. line items, join rows) are omitted — enforce via parents.
 */
export const TENANT_MODELS = new Set<string>([
  'User',
  'Branch',
  'Supplier',
  'Customer',
  'Inventory',
  'Invoice',
  'SalesOrder',
  'StockMovement',
  'Transfer',
  'Purchase',
  'Sale',
  'Repair',
  'RefurbishJob',
  'StockAlert',
  'FileUpload',
  'DeviceHistory',
  'InventoryPart',
  'Expense',
  'Payment',
  'ProfitReport',
  'AIAlert',
  'IntegrationLog',
  'ApiKey',
  'Webhook',
  'Subscription',
  'CompanyUsage',
  'CompanySettings',
  'BarcodeSequence',
  'MarketplaceInstall',
  'Investor',
  'InvestorTransaction',
  'ProfitDistribution',
  'Currency',
  'CurrencyHistory',
  'ExchangeRateHistory',
  'SupplierFxRate',
  'Translation',
  'Warranty',
  'IMEIHistory',
  'IMEIRecord',
  'Incident',
]);

/** Models where non–super-admin users are restricted to their JWT `branchId`. */
export const BRANCH_SCOPED_MODELS = new Set<string>([
  'Inventory',
  'Invoice',
  'SalesOrder',
  'Purchase',
  'Sale',
  'StockMovement',
  'Expense',
  'Payment',
  'Repair',
  'RefurbishJob',
  'AIAlert',
  'ProfitReport',
  'InventoryPart',
]);
