import { prisma } from '../utils/prisma';
import { logger } from '../utils/logger';
import { TtlCache } from '../utils/ttlCache';
import { normalizeUiLanguage, type SupportedUiLanguage } from '../utils/supportedLocale';
import { openAiChatJsonWithCircuitBreaker } from '../selfHealing/openaiCircuit';

type TranslationRow = {
  id: string;
  companyId: string;
  key: string;
  languageCode: string;
  value: string;
  isAutoGenerated: boolean;
  isVerified: boolean;
  createdAt: Date;
  updatedAt: Date;
};

const cache = new TtlCache<string, unknown>({ ttlMs: 10 * 60 * 1000, maxItems: 50_000 });

function cacheKey(parts: Record<string, string | number | boolean | null | undefined>) {
  return Object.entries(parts)
    .map(([k, v]) => `${k}=${String(v ?? '')}`)
    .join('&');
}

async function callOpenAiTranslate(args: {
  sourceText: string;
  sourceLanguage: SupportedUiLanguage;
  targetLanguage: SupportedUiLanguage;
}) {
  const apiKey = String(process.env.OPENAI_API_KEY || '').trim();
  if (!apiKey) return null;
  const model = String(process.env.OPENAI_MODEL || 'gpt-4o-mini').trim();

  const prompt =
    `Translate UI text from ${args.sourceLanguage} to ${args.targetLanguage}.\n` +
    `Rules:\n` +
    `- Return ONLY the translated text (no quotes, no JSON).\n` +
    `- Preserve placeholders like {{count}} or {name} exactly.\n` +
    `- Keep punctuation style natural for the target language.\n\n` +
    `Text:\n${args.sourceText}`;

  try {
    const data = await openAiChatJsonWithCircuitBreaker({
      purpose: 'translations.autoFill',
      model,
      temperature: 0.2,
      messages: [
        { role: 'system', content: 'You are a professional software localization translator.' },
        { role: 'user', content: prompt },
      ],
    });

    const content = String(data?.choices?.[0]?.message?.content || '').trim();
    if (!content) return null;
    return content;
  } catch (err) {
    logger.warn({ err }, '[translations] openai call failed');
    return null;
  }
}

export const translationService = {
  async list(companyId: string, args?: { languageCode?: string; search?: string; limit?: number; offset?: number }) {
    const languageCode = args?.languageCode ? normalizeUiLanguage(args.languageCode) : undefined;
    const search = String(args?.search || '').trim();
    const limit = Math.min(Math.max(Number(args?.limit || 200), 1), 1000);
    const offset = Math.max(Number(args?.offset || 0), 0);

    const where: any = { companyId };
    if (languageCode) where.languageCode = languageCode;
    if (search) {
      where.OR = [
        { key: { contains: search, mode: 'insensitive' } },
        { value: { contains: search, mode: 'insensitive' } },
      ];
    }

    const rows = (await (prisma as any).translation.findMany({
      where,
      orderBy: [{ key: 'asc' }, { languageCode: 'asc' }],
      take: limit,
      skip: offset,
    })) as TranslationRow[];

    return rows;
  },

  async upsert(companyId: string, args: { key: string; languageCode: string; value: string; isVerified?: boolean }) {
    const key = String(args.key || '').trim();
    if (!key) throw new Error('key is required');
    const languageCode = normalizeUiLanguage(args.languageCode);
    const value = String(args.value ?? '').trim();
    if (!value) throw new Error('value is required');

    const isVerified = args.isVerified === true;

    const row = (await (prisma as any).translation.upsert({
      where: { companyId_key_languageCode: { companyId, key, languageCode } },
      update: {
        value,
        isVerified,
        isAutoGenerated: false,
      },
      create: {
        companyId,
        key,
        languageCode,
        value,
        isVerified,
        isAutoGenerated: false,
      },
    })) as TranslationRow;

    cache.delete(cacheKey({ companyId, key, languageCode }));
    return row;
  },

  async setVerified(companyId: string, args: { key: string; languageCode: string; isVerified: boolean }) {
    const key = String(args.key || '').trim();
    if (!key) throw new Error('key is required');
    const languageCode = normalizeUiLanguage(args.languageCode);
    const isVerified = args.isVerified === true;

    const row = (await (prisma as any).translation.update({
      where: { companyId_key_languageCode: { companyId, key, languageCode } },
      data: { isVerified },
    })) as TranslationRow;

    cache.delete(cacheKey({ companyId, key, languageCode }));
    return row;
  },

  async importBulk(companyId: string, args: { languageCode: string; entries: { key: string; value: string }[]; markVerified?: boolean }) {
    const languageCode = normalizeUiLanguage(args.languageCode);
    const entries = Array.isArray(args.entries) ? args.entries : [];
    const markVerified = args.markVerified === true;

    let createdOrUpdated = 0;
    for (const e of entries) {
      const key = String(e?.key || '').trim();
      const value = String(e?.value ?? '').trim();
      if (!key || !value) continue;
      await (prisma as any).translation.upsert({
        where: { companyId_key_languageCode: { companyId, key, languageCode } },
        update: {
          value,
          isVerified: markVerified ? true : undefined,
          isAutoGenerated: false,
        },
        create: {
          companyId,
          key,
          languageCode,
          value,
          isVerified: markVerified ? true : false,
          isAutoGenerated: false,
        },
      });
      createdOrUpdated += 1;
      cache.delete(cacheKey({ companyId, key, languageCode }));
    }
    return { ok: true, languageCode, processed: createdOrUpdated };
  },

  async findMissing(companyId: string, args: { targetLanguageCode: string }) {
    const target = normalizeUiLanguage(args.targetLanguageCode);
    if (target === 'en') return [];

    const enKeys = (await (prisma as any).translation.findMany({
      where: { companyId, languageCode: 'en' },
      select: { key: true },
    })) as { key: string }[];

    const have = (await (prisma as any).translation.findMany({
      where: { companyId, languageCode: target },
      select: { key: true },
    })) as { key: string }[];

    const haveSet = new Set(have.map((x) => x.key));
    return enKeys.map((x) => x.key).filter((k) => !haveSet.has(k));
  },

  async resolve(companyId: string, keyRaw: string, langRaw: string) {
    const key = String(keyRaw || '').trim();
    if (!key) return null;
    const languageCode = normalizeUiLanguage(langRaw);

    const ck = cacheKey({ companyId, key, languageCode });
    const cached = cache.get(ck) as { value: string; source: string } | undefined;
    if (cached) return cached;

    const rows = (await (prisma as any).translation.findMany({
      where: { companyId, key, languageCode: { in: [languageCode, 'en'] } },
      orderBy: [{ isVerified: 'desc' }, { isAutoGenerated: 'asc' }, { updatedAt: 'desc' }],
    })) as TranslationRow[];

    const pick = (lang: string) => rows.filter((r) => r.languageCode === lang);
    const bestLang = pick(languageCode)[0];
    const bestEn = pick('en')[0];

    const out =
      bestLang?.value
        ? { value: bestLang.value, source: bestLang.isVerified ? 'verified' : bestLang.isAutoGenerated ? 'auto' : 'manual' }
        : bestEn?.value
          ? { value: bestEn.value, source: bestEn.isVerified ? 'en_verified' : bestEn.isAutoGenerated ? 'en_auto' : 'en_manual' }
          : null;

    if (out) cache.set(ck, out);
    return out;
  },

  async autoFillMissing(companyId: string, args: { targetLanguageCode: string; limit?: number }) {
    const target = normalizeUiLanguage(args.targetLanguageCode);
    if (target === 'en') return { ok: true, targetLanguageCode: target, created: 0 };

    const limit = Math.min(Math.max(Number(args.limit || 200), 1), 1000);
    const missing = await this.findMissing(companyId, { targetLanguageCode: target });
    const slice = missing.slice(0, limit);

    let created = 0;
    for (const key of slice) {
      const en = (await (prisma as any).translation.findFirst({
        where: { companyId, key, languageCode: 'en' },
        select: { value: true },
      })) as { value?: string } | null;
      const sourceText = String(en?.value || '').trim();
      if (!sourceText) continue;

      const ai = await callOpenAiTranslate({ sourceText, sourceLanguage: 'en', targetLanguage: target });
      if (!ai) continue;
      const value = String(ai).trim();
      if (!value) continue;

      await (prisma as any).translation.upsert({
        where: { companyId_key_languageCode: { companyId, key, languageCode: target } },
        update: { value, isAutoGenerated: true, isVerified: false },
        create: { companyId, key, languageCode: target, value, isAutoGenerated: true, isVerified: false },
      });
      created += 1;
      cache.delete(cacheKey({ companyId, key, languageCode: target }));
    }

    return { ok: true, targetLanguageCode: target, created };
  },
};

